### ISSUE TITLE
linter give error if mocks are used

### ISSUE THREAD

**Issue by fabiosal** [bmewburn/intelephense-docs#14]
Hi,
inteliphense linter is giving error when mocks are used.
```
$orderMock = $this->createMock(Order::class);
$invoice = new Invoice($orderMock);
```

>  [intelephense 10006] Expected type 'App\Order'. Found 'PHPUnit\Framework\MockObject\MockObject'. [E]

**Comment by bmewburn** [comment]
You can avoid this by adding `@var` annotations to identify `$orderMock` type as both `Order` and `MockObject` .

eg
```php
/** @var \App\Order&\PHPUnit\Framework\MockObject\MockObject $orderMock */
$orderMock = $this->createMock(Order::class);
$invoice = new Invoice($orderMock);

**Comment by fabiosal** [comment]
Hi,

the `createMock` method already return a` PHPUnit\Framework\MockObject\MockObject` that extends, in this case, the `App\Order ` class

why  is the annotation necessary ?

thanks

**Comment by bmewburn** [comment]
@fabiosal because the extension can't understand how phpunit generates these. It needs concrete definitions for classes eg `class Order extends MockObject`. Though I think this may be related to https://github.com/bmewburn/vscode-intelephense/issues/867 . If you have the below file in your workspace the extension should be able to understand.

https://github.com/sebastianbergmann/phpunit/blob/1f5e1334bb5de60471251a2392a9cc8d43bc4174/.phpstorm.meta.php

I'll reopen and confirm this works after the release of 1.3.4.

**Comment by bmewburn** [comment]
Working in 1.3.8 with the phpstorm meta file distributed with phpunit.
