### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by astenman** [bmewburn/intelephense-docs#6]
I get the following warning when running intelephense using Emacs and lsp-mode:

```
(node:14388) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at connection.sendRequest.then (c:\Users\anste.NIRADYNAMICS\AppData\Roaming\npm\node_modules\intelephense\node_modules\vscode-languageserver\lib\configuration.js:27:60)
    at <anonymous>
(node:14388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mikebronner** [comment]
@astenman I'm troubleshooting the same  error. Have you found a solution?

**Comment by bmewburn** [comment]
https://github.com/microsoft/vscode-languageserver-node/pull/760 . I think the client is sending an incorrect response here. Should be `any[]` not `null`. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration . PR has been submitted to handle unexpected result safely but should be fixed in the client.
